# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('is_student', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Studentnummer')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='E-mail')),
                ('name', models.CharField(max_length=200, verbose_name='Volledige naam')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Studenten',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2006, '2006-2007'), (2007, '2007-2008'), (2008, '2008-2009'), (2009, '2009-2010'), (2010, '2010-2011'), (2011, '2011-2012'), (2012, '2012-2013'), (2013, '2013-2014'), (2014, '2014-2015'), (2015, '2015-2016'), (2016, '2016-2017'), (2017, '2017-2018'), (2018, '2018-2019'), (2019, '2019-2020'), (2020, '2020-2021'), (2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')], default=2016, verbose_name='Schooljaar')),
                ('quarter', models.IntegerField(choices=[(1, 'Periode 1'), (2, 'Periode 2'), (3, 'Periode 3'), (4, 'Periode 4')], verbose_name='Periode')),
                ('major', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Blok',
                'verbose_name_plural': 'Blokken',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twin.Term', verbose_name='Volgend blok'),
        ),
        migrations.AddField(
            model_name='preference',
            name='preference_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_for', to='twin.Student'),
        ),
        migrations.AddField(
            model_name='preference',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twin.Student'),
        ),
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twin.Student'),
        ),
    ]
