# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preference',
            options={'ordering': ['student'], 'verbose_name': 'Voorkeur', 'verbose_name_plural': 'Voorkeuren'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Studenten'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='term',
        ),
        migrations.AlterField(
            model_name='preference',
            name='preference_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_for', to='twin.Student', verbose_name='Heeft voorkeur voor'),
        ),
    ]
